In [123]:
import numpy as np
import pandas as pd

## Part 1: Load the Data

In [124]:
# import CSV files
df_coffee_export = pd.read_csv("Coffee_export-1.csv")
df_coffee_import = pd.read_csv("Coffee_import-1.csv")
df_coffee_production = pd.read_csv("Coffee_production-1.csv")

# print(df_coffee_export.head())
# print(df_coffee_import.head())
# print(df_coffee_production.head())

## Part 2: Explore the Data

In [125]:
# methods
# pick up at index for data cleaning to skip word-labels
def spanOfYearsRepresented(df, index=1):
    array = df.columns.values.to_numpy()
    for i, item in enumerate(array):
        if i < index:
            continue
        array[i] = item[0:4]
        # print(array[i])
    start = int(array[index])
    end = int(array[-2])
    print(end - start, "consecutive years,")
    print(array[index], " through ", array[-2])

### Explore coffee export data

In [126]:
# 1. coffee exports has 55 rows and 32 columns (records for 55 countries)
# row and column counts from `.shape`:
print("df_coffee_export shape: ", df_coffee_export.shape)
print("**************************")
# 2. identify column names using `.column`:
print("df_coffee_export column labels: ", df_coffee_export.columns)

df_coffee_export shape:  (55, 32)
**************************
df_coffee_export column labels:  Index(['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', 'Total_export'],
      dtype='str')

In [127]:
# 3. data types are `int64(31), str(1)` (string is column labels, rest of the data set is int64)
df_coffee_export.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       55 non-null     str
 1   1990          55 non-null     int64
 2   1991          55 non-null     int64
 3   1992          55 non-null     int64
 4   1993          55 non-null     int64
 5   1994          55 non-null     int64
 6   1995          55 non-null     int64
 7   1996          55 non-null     int64
 8   1997          55 non-null     int64
 9   1998          55 non-null     int64
 10  1999          55 non-null     int64
 11  2000          55 non-null     int64
 12  2001          55 non-null     int64
 13  2002          55 non-null     int64
 14  2003          55 non-null     int64
 15  2004          55 non-null     int64
 16  2005          55 non-null     int64
 17  2006          55 non-null     int64
 18  2007          55 non-null     int64
 19  2008          55 non-null     int64
 20  2009          55 non-null     int64
 21  2010          55 non-null     int64
 22  2011          55 non-null     int64
 23  2012          55 non-null     int64
 24  2013          55 non-null     int64
 25  2014          55 non-null     int64
 26  2015          55 non-null     int64
 27  2016          55 non-null     int64
 28  2017          55 non-null     int64
 29  2018          55 non-null     int64
 30  2019          55 non-null     int64
 31  Total_export  55 non-null     int64
dtypes: int64(31), str(1)
memory usage: 13.9 KB

In [128]:
df_coffee_export.columns.tolist()

['Country',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 'Total_export']

In [129]:
# 4. missing values?
df_coffee_export.isnull().sum() 
# print("any null: ", df_coffee_export.isnull().sum())
print("total null: ", df_coffee_export.isnull().sum().sum())
# print("any na: ", df_coffee_export.isna().sum())
print("total na: ", df_coffee_export.isna().sum().sum())
print("duplicates: ", df_coffee_export.duplicated().sum())
print("**************************")
# 5. span of years represented
spanOfYearsRepresented(df_coffee_export)
print("**************************")
# 6. countries included:
values = df_coffee_export.loc[:, 'Country'].tolist()
print(*values, sep=", ")
print("**************************")
print(np.array2string(np.array(values), separator=", ", max_line_width=80)) #I asked ChatGPT for this one, how to get it in a chunk instead of a long line, using numpy or pandas

total null:  0
total na:  0
duplicates:  0
**************************
29 consecutive years,
1990  through  2019
**************************
Angola, Bolivia (Plurinational State of), Brazil, Burundi, Cameroon, Central African Republic, Colombia, Congo, Costa Rica, Côte d'Ivoire, Cuba, Democratic Republic of Congo, Dominican Republic, Ecuador, El Salvador, Equatorial Guinea, Ethiopia, Gabon, Ghana, Guatemala, Guinea, Guyana, Haiti, Honduras, India, Indonesia, Jamaica, Kenya, Lao People's Democratic Republic, Liberia, Madagascar, Malawi, Mexico, Nepal, Nicaragua, Nigeria, Panama, Papua New Guinea, Paraguay, Peru, Philippines, Rwanda, Sierra Leone, Sri Lanka, Tanzania, Thailand, Timor-Leste, Togo, Trinidad & Tobago, Uganda, Venezuela, Viet Nam, Yemen, Zambia, Zimbabwe
**************************
['Angola', 'Bolivia (Plurinational State of)', 'Brazil', 'Burundi', 'Cameroon',
 'Central African Republic', 'Colombia', 'Congo', 'Costa Rica', "Côte d'Ivoire",
 'Cuba', 'Democratic Republic of Congo', 'Dominican Republic', 'Ecuador',
 'El Salvador', 'Equatorial Guinea', 'Ethiopia', 'Gabon', 'Ghana', 'Guatemala',
 'Guinea', 'Guyana', 'Haiti', 'Honduras', 'India', 'Indonesia', 'Jamaica',
 'Kenya', "Lao People's Democratic Republic", 'Liberia', 'Madagascar', 'Malawi',
 'Mexico', 'Nepal', 'Nicaragua', 'Nigeria', 'Panama', 'Papua New Guinea',
 'Paraguay', 'Peru', 'Philippines', 'Rwanda', 'Sierra Leone', 'Sri Lanka',
 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Trinidad & Tobago', 'Uganda',
 'Venezuela', 'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe']

### Explore coffee import data

In [131]:
# 1. coffee imports has 35 rows and 32 columns (35 countries recorded)
# row and column counts from `.shape`:
print("df_coffee_import shape: ", df_coffee_import.shape)
print("**************************")
# 2. identify column names using `.column`:
print("df_coffee_import column labels: ", df_coffee_import.columns)

df_coffee_import shape:  (35, 32)
**************************
df_coffee_import column labels:  Index(['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', 'Total_import'],
      dtype='str')

In [132]:
# 3. data types are `int64(31), str(1)` (string is column labels, rest of the data set is int64)
df_coffee_import.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       35 non-null     str
 1   1990          35 non-null     int64
 2   1991          35 non-null     int64
 3   1992          35 non-null     int64
 4   1993          35 non-null     int64
 5   1994          35 non-null     int64
 6   1995          35 non-null     int64
 7   1996          35 non-null     int64
 8   1997          35 non-null     int64
 9   1998          35 non-null     int64
 10  1999          35 non-null     int64
 11  2000          35 non-null     int64
 12  2001          35 non-null     int64
 13  2002          35 non-null     int64
 14  2003          35 non-null     int64
 15  2004          35 non-null     int64
 16  2005          35 non-null     int64
 17  2006          35 non-null     int64
 18  2007          35 non-null     int64
 19  2008          35 non-null     int64
 20  2009          35 non-null     int64
 21  2010          35 non-null     int64
 22  2011          35 non-null     int64
 23  2012          35 non-null     int64
 24  2013          35 non-null     int64
 25  2014          35 non-null     int64
 26  2015          35 non-null     int64
 27  2016          35 non-null     int64
 28  2017          35 non-null     int64
 29  2018          35 non-null     int64
 30  2019          35 non-null     int64
 31  Total_import  35 non-null     int64
dtypes: int64(31), str(1)
memory usage: 8.9 KB

In [133]:
# 4. missing values?
df_coffee_import.isnull().sum() 
# print("any null: ", df_coffee_import.isnull().sum())
print("total null: ", df_coffee_import.isnull().sum().sum())
# print("any na: ", df_coffee_import.isna().sum())
print("total na: ", df_coffee_import.isna().sum().sum())
print("duplicates: ", df_coffee_import.duplicated().sum())
print("**************************")
# 5. span of years represented
spanOfYearsRepresented(df_coffee_import)
print("**************************")
# 6. countries included:
values = df_coffee_import.loc[:, 'Country'].tolist()
print(*values, sep=", ")
print("**************************")
print(np.array2string(np.array(values), separator=", ", max_line_width=80))

total null:  0
total na:  0
duplicates:  0
**************************
29 consecutive years,
1990  through  2019
**************************
   Austria,    Belgium,    Belgium/Luxembourg,    Bulgaria,    Croatia,    Cyprus,    Czechia,    Denmark,    Estonia,    Finland,    France,    Germany,    Greece,    Hungary,    Ireland,    Italy,    Latvia,    Lithuania,    Luxembourg,    Malta,    Netherlands,    Poland,    Portugal,    Romania,    Slovakia,    Slovenia,    Spain,    Sweden, Japan, Norway, Russian Federation, Switzerland, Tunisia, United Kingdom, United States of America
**************************
['   Austria', '   Belgium', '   Belgium/Luxembourg', '   Bulgaria',
 '   Croatia', '   Cyprus', '   Czechia', '   Denmark', '   Estonia',
 '   Finland', '   France', '   Germany', '   Greece', '   Hungary',
 '   Ireland', '   Italy', '   Latvia', '   Lithuania', '   Luxembourg',
 '   Malta', '   Netherlands', '   Poland', '   Portugal', '   Romania',
 '   Slovakia', '   Slovenia', '   Spain', '   Sweden', 'Japan', 'Norway',
 'Russian Federation', 'Switzerland', 'Tunisia', 'United Kingdom',
 'United States of America']

### Explore coffee production data

In [134]:
# 1. coffee production has 55 rows and 32 columns
# row and column counts from `.shape`:
print("df_coffee_production shape: ", df_coffee_production.shape)
print("**************************")
# 2. identify column names using `.column`:
print("df_coffee_production column labels: ", df_coffee_production.columns)

df_coffee_production shape:  (55, 33)
**************************
df_coffee_production column labels:  Index(['Country', 'Coffee type', '1990/91', '1991/92', '1992/93', '1993/94',
       '1994/95', '1995/96', '1996/97', '1997/98', '1998/99', '1999/00',
       '2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06',
       '2006/07', '2007/08', '2008/09', '2009/10', '2010/11', '2011/12',
       '2012/13', '2013/14', '2014/15', '2015/16', '2016/17', '2017/18',
       '2018/19', '2019/20', 'Total_production'],
      dtype='str')

In [135]:
# 3. data types are `int64(31), str(2)` (string is column labels, rest of the data set is int64)
df_coffee_production.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           55 non-null     str
 1   Coffee type       55 non-null     str
 2   1990/91           55 non-null     float64
 3   1991/92           55 non-null     float64
 4   1992/93           55 non-null     float64
 5   1993/94           55 non-null     float64
 6   1994/95           55 non-null     float64
 7   1995/96           55 non-null     float64
 8   1996/97           55 non-null     float64
 9   1997/98           55 non-null     float64
 10  1998/99           55 non-null     float64
 11  1999/00           55 non-null     float64
 12  2000/01           55 non-null     float64
 13  2001/02           55 non-null     float64
 14  2002/03           55 non-null     float64
 15  2003/04           55 non-null     float64
 16  2004/05           55 non-null     float64
 17  2005/06           55 non-null     float64
 18  2006/07           55 non-null     float64
 19  2007/08           55 non-null     float64
 20  2008/09           55 non-null     float64
 21  2009/10           55 non-null     float64
 22  2010/11           55 non-null     float64
 23  2011/12           55 non-null     float64
 24  2012/13           55 non-null     float64
 25  2013/14           55 non-null     float64
 26  2014/15           55 non-null     float64
 27  2015/16           55 non-null     float64
 28  2016/17           55 non-null     float64
 29  2017/18           55 non-null     float64
 30  2018/19           55 non-null     float64
 31  2019/20           55 non-null     float64
 32  Total_production  55 non-null     float64
dtypes: float64(31), str(2)
memory usage: 14.3 KB

In [136]:
# 4. missing values?
df_coffee_production.isnull().sum() 
# print("any null: ", df_coffee_production.isnull().sum())
print("total null: ", df_coffee_production.isnull().sum().sum())
# print("any na: ", df_coffee_production.isna().sum())
print("total na: ", df_coffee_production.isna().sum().sum())
print("duplicates: ", df_coffee_export.duplicated().sum())
print("**************************")
# 5. span of years represented
# note: technically this data went through 2020, but since the record-keeping was staggered to be calculated starting mid-year, I included the first year and left off the last
# so, 1990/91 through 2019/20 was calculated as 1990-2019
spanOfYearsRepresented(df_coffee_production, 2)
print("**************************")
# 6. countries included:
values = df_coffee_production.loc[:, 'Country'].tolist()
print(*values, sep=", ")
print("**************************")
print(np.array2string(np.array(values), separator=", ", max_line_width=80))

total null:  0
total na:  0
duplicates:  0
**************************
29 consecutive years,
1990  through  2019
**************************
Angola, Bolivia (Plurinational State of), Brazil, Burundi, Ecuador, Indonesia, Madagascar, Malawi, Papua New Guinea, Paraguay, Peru, Rwanda, Timor-Leste, Zimbabwe, Congo, Cuba, Dominican Republic, Haiti, Philippines, Tanzania, Zambia, Cameroon, Central African Republic, Colombia, Costa Rica, Côte d'Ivoire, Democratic Republic of Congo, El Salvador, Equatorial Guinea, Ethiopia, Gabon, Ghana, Guatemala, Guinea, Guyana, Honduras, India, Jamaica, Kenya, Lao People's Democratic Republic, Liberia, Mexico, Nepal, Nicaragua, Nigeria, Panama, Sierra Leone, Sri Lanka, Thailand, Togo, Trinidad & Tobago, Uganda, Venezuela, Viet Nam, Yemen
**************************
['Angola', 'Bolivia (Plurinational State of)', 'Brazil', 'Burundi', 'Ecuador',
 'Indonesia', 'Madagascar', 'Malawi', 'Papua New Guinea', 'Paraguay', 'Peru',
 'Rwanda', 'Timor-Leste', 'Zimbabwe', 'Congo', 'Cuba', 'Dominican Republic',
 'Haiti', 'Philippines', 'Tanzania', 'Zambia', 'Cameroon',
 'Central African Republic', 'Colombia', 'Costa Rica', "Côte d'Ivoire",
 'Democratic Republic of Congo', 'El Salvador', 'Equatorial Guinea', 'Ethiopia',
 'Gabon', 'Ghana', 'Guatemala', 'Guinea', 'Guyana', 'Honduras', 'India',
 'Jamaica', 'Kenya', "Lao People's Democratic Republic", 'Liberia', 'Mexico',
 'Nepal', 'Nicaragua', 'Nigeria', 'Panama', 'Sierra Leone', 'Sri Lanka',
 'Thailand', 'Togo', 'Trinidad & Tobago', 'Uganda', 'Venezuela', 'Viet Nam',
 'Yemen']

## Part 3: Descriptive Statistics

In [137]:
export_statistics = df_coffee_export.describe(include=[np.number])
# export_statistics = df_coffee_export.describe(include="all")
export_statistics

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Tota
count,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,...,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01
mean,8.800800e+07,8.284691e+07,8.541382e+07,8.200036e+07,7.713600e+07,7.404436e+07,8.472982e+07,8.775055e+07,8.753673e+07,9.397091e+07,...,1.114767e+08,1.183015e+08,1.184389e+08,4.627702e+07,4.695557e+07,1.323622e+08,1.303887e+08,1.381047e+08,6.021884e+07,2.851332e+09
std,1.832890e+08,2.019180e+08,2.031566e+08,1.852049e+08,1.719033e+08,1.471032e+08,1.634044e+08,1.761129e+08,1.836647e+08,2.146255e+08,...,3.121420e+08,3.032438e+08,3.130926e+08,3.818677e+08,3.713066e+08,3.763857e+08,3.407518e+08,3.927493e+08,3.977899e+08,6.261177e+09
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,-2.147484e+09,-2.147484e+09,0.000000e+00,0.000000e+00,0.000000e+00,-2.147484e+09,1.500000e+06
25%,4.020000e+06,3.960000e+06,2.310000e+06,2.220000e+06,1.860000e+06,2.370000e+06,1.680000e+06,2.220000e+06,1.800000e+06,2.220000e+06,...,5.400000e+05,4.500000e+05,3.600000e+05,5.700000e+05,4.500000e+05,6.600000e+05,5.700000e+05,5.100000e+05,3.900000e+05,6.084000e+07
50%,1.578000e+07,9.300000e+06,9.960000e+06,1.308000e+07,9.180000e+06,1.200000e+07,9.360000e+06,1.218000e+07,1.284000e+07,1.806000e+07,...,7.920000e+06,8.220000e+06,4.200000e+06,3.720000e+06,3.540000e+06,4.560000e+06,3.480000e+06,6.660000e+06,3.180000e+06,3.160800e+08
75%,1.055700e+08,8.502000e+07,7.971000e+07,7.818000e+07,8.499000e+07,8.970000e+07,1.055100e+08,9.048000e+07,9.099000e+07,9.414000e+07,...,8.133000e+07,8.862000e+07,7.818000e+07,5.808000e+07,4.743000e+07,6.420000e+07,4.947000e+07,6.234000e+07,5.625000e+07,2.552670e+09
max,1.016160e+09,1.270980e+09,1.127460e+09,1.070280e+09,1.036380e+09,8.680800e+08,9.150600e+08,1.008060e+09,1.088640e+09,1.388940e+09,...,2.028360e+09,1.712940e+09,1.899060e+09,1.565820e+09,1.316640e+09,2.056140e+09,1.855500e+09,2.138220e+09,1.644000e+09,3.380771e+10

In [138]:
df_coffee_export.describe().loc["max"]
# print(df_coffee_export.max())
df_coffee_export.describe().loc["min"]
df_coffee_export.describe().loc["mean"]

1990    8.800800e+07
1991    8.284691e+07
1992    8.541382e+07
1993    8.200036e+07
1994    7.713600e+07
1995    7.404436e+07
1996    8.472982e+07
1997    8.775055e+07
1998    8.753673e+07
1999    9.397091e+07
2000    9.770727e+07
2001    9.912000e+07
2002    9.691855e+07
2003    9.422618e+07
2004    9.938073e+07
2005    9.552436e+07
2006    1.001029e+08
2007    1.050524e+08
2008    1.064716e+08
2009    1.049945e+08
2010    1.058716e+08
2011    1.114767e+08
2012    1.183015e+08
2013    1.184389e+08
2014    4.627702e+07
2015    4.695557e+07
2016    1.323622e+08
2017    1.303887e+08
2018    1.381047e+08
2019    6.021884e+07
Tota    2.851332e+09
Name: mean, dtype: float64

In [139]:
import_statistics = df_coffee_import.describe(include=[np.number])
import_statistics

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Tota
count,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,...,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01
mean,1.270834e+08,1.221943e+08,1.357989e+08,1.322023e+08,1.286126e+08,1.240646e+08,1.334674e+08,1.389651e+08,1.418863e+08,1.464549e+08,...,1.916794e+08,1.940109e+08,1.987337e+08,2.057606e+08,2.080800e+08,2.187960e+08,2.161097e+08,2.227629e+08,2.313326e+08,5.069693e+09
std,2.543488e+08,2.435393e+08,2.690354e+08,2.424808e+08,2.178530e+08,2.188911e+08,2.415144e+08,2.500391e+08,2.548447e+08,2.715283e+08,...,3.363666e+08,3.404099e+08,3.453368e+08,3.539295e+08,3.511787e+08,3.667628e+08,3.684394e+08,3.678250e+08,3.854538e+08,8.850559e+09
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.970000e+07
25%,6.300000e+05,4.800000e+05,6.180000e+06,7.890000e+06,8.880000e+06,8.550000e+06,9.750000e+06,1.074000e+07,1.077000e+07,1.176000e+07,...,2.151000e+07,2.163000e+07,2.373000e+07,2.499000e+07,2.595000e+07,2.835000e+07,2.613000e+07,2.937000e+07,2.946000e+07,5.573100e+08
50%,3.444000e+07,3.150000e+07,3.618000e+07,4.008000e+07,4.626000e+07,3.798000e+07,4.458000e+07,4.362000e+07,4.572000e+07,4.740000e+07,...,5.712000e+07,6.456000e+07,6.378000e+07,6.360000e+07,6.264000e+07,6.804000e+07,6.564000e+07,6.960000e+07,7.320000e+07,1.640040e+09
75%,1.168500e+08,1.141200e+08,1.210200e+08,1.169700e+08,1.246500e+08,1.251600e+08,1.335000e+08,1.439100e+08,1.546500e+08,1.491000e+08,...,2.276100e+08,2.300700e+08,2.283900e+08,2.500500e+08,2.665800e+08,2.949900e+08,3.017100e+08,3.242400e+08,3.272400e+08,5.841240e+09
max,1.260420e+09,1.190400e+09,1.376340e+09,1.159740e+09,9.702600e+08,1.026420e+09,1.166700e+09,1.220580e+09,1.261800e+09,1.364760e+09,...,1.565580e+09,1.563360e+09,1.620960e+09,1.653900e+09,1.662480e+09,1.730280e+09,1.769280e+09,1.735080e+09,1.851240e+09,4.250766e+10

In [140]:
df_coffee_import.describe().loc["max"]
# print(df_coffee_import.max())
df_coffee_import.describe().loc["min"]
df_coffee_import.describe().loc["mean"]

1990    1.270834e+08
1991    1.221943e+08
1992    1.357989e+08
1993    1.322023e+08
1994    1.286126e+08
1995    1.240646e+08
1996    1.334674e+08
1997    1.389651e+08
1998    1.418863e+08
1999    1.464549e+08
2000    1.502417e+08
2001    1.524840e+08
2002    1.564560e+08
2003    1.601109e+08
2004    1.643057e+08
2005    1.652177e+08
2006    1.741200e+08
2007    1.794103e+08
2008    1.830771e+08
2009    1.791651e+08
2010    1.871091e+08
2011    1.916794e+08
2012    1.940109e+08
2013    1.987337e+08
2014    2.057606e+08
2015    2.080800e+08
2016    2.187960e+08
2017    2.161097e+08
2018    2.227629e+08
2019    2.313326e+08
Tota    5.069693e+09
Name: mean, dtype: float64

In [141]:
production_statistics = df_coffee_production.describe(include=[np.number])
production_statistics

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Tota
count,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,...,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01
mean,1.017055e+08,1.104753e+08,1.074775e+08,1.001007e+08,1.017971e+08,9.525927e+07,1.127029e+08,1.089676e+08,1.187629e+08,1.433280e+08,...,1.541749e+08,1.649280e+08,1.679007e+08,1.639625e+08,1.703193e+08,1.770742e+08,1.785742e+08,1.881415e+08,1.800578e+08,4.104269e+09
std,2.510875e+08,2.668466e+08,3.022180e+08,2.489344e+08,2.510328e+08,1.858680e+08,2.602192e+08,2.430145e+08,3.142337e+08,4.012591e+08,...,4.469919e+08,4.931417e+08,5.030529e+08,4.918727e+08,5.059698e+08,5.225472e+08,5.135587e+08,5.851111e+08,5.390922e+08,1.112550e+10
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.080000e+06
25%,2.430000e+06,3.900000e+06,2.640000e+06,2.130000e+06,2.610000e+06,2.610000e+06,2.340000e+06,2.880000e+06,3.480000e+06,3.540000e+06,...,1.980000e+06,1.710000e+06,2.010000e+06,2.250000e+06,2.310000e+06,1.890000e+06,2.160000e+06,2.190000e+06,2.280000e+06,8.199000e+07
50%,2.766000e+07,2.778000e+07,3.000000e+07,2.652000e+07,2.436000e+07,2.604000e+07,2.406000e+07,1.800000e+07,2.634000e+07,2.184000e+07,...,2.094000e+07,2.004000e+07,1.548000e+07,1.488000e+07,1.758000e+07,1.620000e+07,1.584000e+07,1.860000e+07,1.842000e+07,6.236400e+08
75%,9.216000e+07,9.720000e+07,9.234000e+07,9.486000e+07,1.153200e+08,1.127700e+08,1.139700e+08,9.669000e+07,1.076700e+08,1.211700e+08,...,9.735000e+07,9.189000e+07,7.185000e+07,6.960000e+07,6.657000e+07,6.864000e+07,7.053000e+07,7.806000e+07,7.194000e+07,2.785140e+09
max,1.637160e+09,1.637580e+09,2.076180e+09,1.690020e+09,1.691520e+09,1.083600e+09,1.751820e+09,1.568880e+09,2.205660e+09,2.854680e+09,...,2.915520e+09,3.325080e+09,3.281340e+09,3.198300e+09,3.172260e+09,3.407280e+09,3.164400e+09,3.907860e+09,3.492660e+09,7.508298e+10

In [142]:
df_coffee_production.describe().loc["max"]
# print(df_coffee_production.max())
df_coffee_production.describe().loc["min"]
df_coffee_production.describe().loc["mean"]

1990    1.017055e+08
1991    1.104753e+08
1992    1.074775e+08
1993    1.001007e+08
1994    1.017971e+08
1995    9.525927e+07
1996    1.127029e+08
1997    1.089676e+08
1998    1.187629e+08
1999    1.433280e+08
2000    1.240844e+08
2001    1.177113e+08
2002    1.337727e+08
2003    1.150942e+08
2004    1.266316e+08
2005    1.212742e+08
2006    1.477091e+08
2007    1.329185e+08
2008    1.470556e+08
2009    1.394989e+08
2010    1.528091e+08
2011    1.541749e+08
2012    1.649280e+08
2013    1.679007e+08
2014    1.639625e+08
2015    1.703193e+08
2016    1.770742e+08
2017    1.785742e+08
2018    1.881415e+08
2019    1.800578e+08
Tota    4.104269e+09
Name: mean, dtype: float64

## Part 4: Data Quality Assessment

Was not able to find missing values or duplicate rows. There were values of "0" however, which while being the correct data type indicate data absence. (No exports in some cases.) This could indicate exports were simply not recorded these years. If exports were not recorded for a significant number of years but exports did in fact happen, it may be wise to do metrics excluding these countries so that their impact on coffee production is not minimized.

Coffee production data has another idiosynchracy: instead of `int64` datatype, `float64` is used. It's unlikely that this adds anything to the dataset since digits right of the decimal are 0 (doublecheck this is 100% accurate across the dataset before taking action).

The production dataset had an odd indexing habit of using "year/year" instead of a single "year", as was done with imports and exports. Instead of "1990", production seemed to be calculated mid-year through next mid-year, "1990/91". This required a cleaning function to synchronize labeling.

## Part 5: Initial Insights

Our coffee import is the most thorough dataset we have. It lists extensive data for imports from 55 countries. The Coffee Production dataset will require the most extensive cleaning since it has labels and data types inconsistent with the other two datasets.I would be interested to know why we do not have data for certain countries during certain periods. Are we missing any business opportunities by being distracted elsewhere? What is the significance of countries that both import and export coffee? Should we consider these countries as potential business competition? Are there any countries that exclusively import coffee where we might find potential business opportunities?