In [ ]:
import sys
# print(sys.executable)

import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

## Part 1 – Load and Inspect the Datasets

In [2]:
# load csv files into pandas data frames
coffee_exp = pd.read_csv("coffee_ex.csv")
coffee_imp = pd.read_csv("coffee_imp.csv")
coffee_prod = pd.read_csv("coffee_prod.csv")

### Inspect data sets (.shape, .dtypes)

In [3]:
# inspect the data with `.shape`
print("exports: ",coffee_exp.shape," imports: ",coffee_imp.shape," production: ",coffee_prod.shape)

exports:  (55, 32)  imports:  (35, 32)  production:  (55, 33)

In [4]:
# inspect the data with `.dtypes`
print("exports: ", coffee_exp.dtypes," imports: ", coffee_imp.dtypes," production: ", coffee_prod.dtypes) # note the float64 instead of int64 in production

exports:  Country           str
1990            int64
1991            int64
1992            int64
1993            int64
1994            int64
1995            int64
1996            int64
1997            int64
1998            int64
1999            int64
2000            int64
2001            int64
2002            int64
2003            int64
2004            int64
2005            int64
2006            int64
2007            int64
2008            int64
2009            int64
2010            int64
2011            int64
2012            int64
2013            int64
2014            int64
2015            int64
2016            int64
2017            int64
2018            int64
2019            int64
Total_export    int64
dtype: object  imports:  Country           str
1990            int64
1991            int64
1992            int64
1993            int64
1994            int64
1995            int64
1996            int64
1997            int64
1998            int64
1999            int64
2000            int64
2001            int64
2002            int64
2003            int64
2004            int64
2005            int64
2006            int64
2007            int64
2008            int64
2009            int64
2010            int64
2011            int64
2012            int64
2013            int64
2014            int64
2015            int64
2016            int64
2017            int64
2018            int64
2019            int64
Total_import    int64
dtype: object  production:  Country                 str
Coffee type             str
1990/91             float64
1991/92             float64
1992/93             float64
1993/94             float64
1994/95             float64
1995/96             float64
1996/97             float64
1997/98             float64
1998/99             float64
1999/00             float64
2000/01             float64
2001/02             float64
2002/03             float64
2003/04             float64
2004/05             float64
2005/06             float64
2006/07             float64
2007/08             float64
2008/09             float64
2009/10             float64
2010/11             float64
2011/12             float64
2012/13             float64
2013/14             float64
2014/15             float64
2015/16             float64
2016/17             float64
2017/18             float64
2018/19             float64
2019/20             float64
Total_production    float64
dtype: object

### print unique countries list

In [5]:
coffee_exp["Country"]

0                               Angola
1     Bolivia (Plurinational State of)
2                               Brazil
3                              Burundi
4                             Cameroon
5             Central African Republic
6                             Colombia
7                                Congo
8                           Costa Rica
9                        Côte d'Ivoire
10                                Cuba
11        Democratic Republic of Congo
12                  Dominican Republic
13                             Ecuador
14                         El Salvador
15                   Equatorial Guinea
16                            Ethiopia
17                               Gabon
18                               Ghana
19                           Guatemala
20                              Guinea
21                              Guyana
22                               Haiti
23                            Honduras
24                               India
25                           Indonesia
26                             Jamaica
27                               Kenya
28    Lao People's Democratic Republic
29                             Liberia
30                          Madagascar
31                              Malawi
32                              Mexico
33                               Nepal
34                           Nicaragua
35                             Nigeria
36                              Panama
37                    Papua New Guinea
38                            Paraguay
39                                Peru
40                         Philippines
41                              Rwanda
42                        Sierra Leone
43                           Sri Lanka
44                            Tanzania
45                            Thailand
46                         Timor-Leste
47                                Togo
48                   Trinidad & Tobago
49                              Uganda
50                           Venezuela
51                            Viet Nam
52                               Yemen
53                              Zambia
54                            Zimbabwe
Name: Country, dtype: str

In [6]:
coffee_imp["Country"] #note that less countries recorded importing than exporting

0                      Austria
1                      Belgium
2           Belgium/Luxembourg
3                     Bulgaria
4                      Croatia
5                       Cyprus
6                      Czechia
7                      Denmark
8                      Estonia
9                      Finland
10                      France
11                     Germany
12                      Greece
13                     Hungary
14                     Ireland
15                       Italy
16                      Latvia
17                   Lithuania
18                  Luxembourg
19                       Malta
20                 Netherlands
21                      Poland
22                    Portugal
23                     Romania
24                    Slovakia
25                    Slovenia
26                       Spain
27                      Sweden
28                       Japan
29                      Norway
30          Russian Federation
31                 Switzerland
32                     Tunisia
33              United Kingdom
34    United States of America
Name: Country, dtype: str

In [7]:
coffee_prod["Country"]

0                               Angola
1     Bolivia (Plurinational State of)
2                               Brazil
3                              Burundi
4                              Ecuador
5                            Indonesia
6                           Madagascar
7                               Malawi
8                     Papua New Guinea
9                             Paraguay
10                                Peru
11                              Rwanda
12                         Timor-Leste
13                            Zimbabwe
14                               Congo
15                                Cuba
16                  Dominican Republic
17                               Haiti
18                         Philippines
19                            Tanzania
20                              Zambia
21                            Cameroon
22            Central African Republic
23                            Colombia
24                          Costa Rica
25                       Côte d'Ivoire
26        Democratic Republic of Congo
27                         El Salvador
28                   Equatorial Guinea
29                            Ethiopia
30                               Gabon
31                               Ghana
32                           Guatemala
33                              Guinea
34                              Guyana
35                            Honduras
36                               India
37                             Jamaica
38                               Kenya
39    Lao People's Democratic Republic
40                             Liberia
41                              Mexico
42                               Nepal
43                           Nicaragua
44                             Nigeria
45                              Panama
46                        Sierra Leone
47                           Sri Lanka
48                            Thailand
49                                Togo
50                   Trinidad & Tobago
51                              Uganda
52                           Venezuela
53                            Viet Nam
54                               Yemen
Name: Country, dtype: str

In [8]:
coffee_exp.index # "rows". and remember .loc and .iloc for rows
# coffee_exp.columns

RangeIndex(start=0, stop=55, step=1)

In [9]:
# 32, 32, 33 columns:
print("exports: ",coffee_exp.columns," imports: ",coffee_imp.columns," production: ",coffee_prod.columns)
# coffee_exp.columns 
# coffee_imp.columns
coffee_prod.columns

exports:  Index(['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', 'Total_export'],
      dtype='str')  imports:  Index(['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', 'Total_import'],
      dtype='str')  production:  Index(['Country', 'Coffee type', '1990/91', '1991/92', '1992/93', '1993/94',
       '1994/95', '1995/96', '1996/97', '1997/98', '1998/99', '1999/00',
       '2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06',
       '2006/07', '2007/08', '2008/09', '2009/10', '2010/11', '2011/12',
       '2012/13', '2013/14', '2014/15', '2015/16', '2016/17', '2017/18',
       '2018/19', '2019/20', 'Total_production'],
      dtype='str')

Index(['Country', 'Coffee type', '1990/91', '1991/92', '1992/93', '1993/94',
       '1994/95', '1995/96', '1996/97', '1997/98', '1998/99', '1999/00',
       '2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06',
       '2006/07', '2007/08', '2008/09', '2009/10', '2010/11', '2011/12',
       '2012/13', '2013/14', '2014/15', '2015/16', '2016/17', '2017/18',
       '2018/19', '2019/20', 'Total_production'],
      dtype='str')

## Part 2 – Assess Data Quality and Structural Inconsistencies

### check for missing values (NaN, None, NaT)

In [10]:
coffee_exp.isna().sum()
coffee_imp.isna().sum()
coffee_prod.isna().sum()

Country             0
Coffee type         0
1990/91             0
1991/92             0
1992/93             0
1993/94             0
1994/95             0
1995/96             0
1996/97             0
1997/98             0
1998/99             0
1999/00             0
2000/01             0
2001/02             0
2002/03             0
2003/04             0
2004/05             0
2005/06             0
2006/07             0
2007/08             0
2008/09             0
2009/10             0
2010/11             0
2011/12             0
2012/13             0
2013/14             0
2014/15             0
2015/16             0
2016/17             0
2017/18             0
2018/19             0
2019/20             0
Total_production    0
dtype: int64

### checking for null

In [11]:
# exports
# coffee_exp['1999'].isnull() #try df.notnull() later
coffee_exp["1990"].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
Name: 1990, dtype: bool

In [12]:
# taking a moment to think about slices and sections
# df.iloc[ start : stop(before) : step ]
# df.iloc[rows, columns]
coffee_exp.iloc[0,0] #first row, first column
coffee_exp.iloc[0,:] #first row, all columns
coffee_exp.iloc[:,0] #all rows, first column
coffee_exp.iloc[:, 2:4] #all rows, columns 2-4
coffee_exp.iloc[:,10:21]

,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009
0,3000000,1320000,840000,540000,1020000,360000,300000,300000,240000,360000,420000
1,7440000,6360000,4200000,4740000,4380000,5580000,5040000,5580000,5040000,4080000,4980000
2,1388940000,1080960000,1390320000,1678920000,1542660000,1588680000,1571880000,1642140000,1691040000,1770600000,1822680000
3,24540000,26640000,18180000,17340000,28560000,20340000,22260000,16860000,21360000,15060000,17340000
4,69240000,72300000,67500000,38400000,48840000,44040000,42240000,44340000,43260000,31620000,37080000
5,11700000,12180000,5640000,5700000,2400000,3840000,2820000,1020000,7320000,1980000,3720000
6,599700000,550620000,596640000,616380000,614640000,611640000,652260000,656700000,678000000,665100000,473640000
7,0,0,0,0,0,0,0,0,0,0,0
8,131700000,117900000,121080000,107040000,102120000,85440000,88800000,78600000,81840000,86400000,74160000
9,144360000,366600000,245700000,195180000,158820000,154380000,105240000,105060000,131760000,89400000,108420000
10,4620000,6780000,6540000,3420000,3000000,1500000,1440000,960000,960000,240000,420000
11,29220000,16860000,7980000,10740000,12720000,15180000,9480000,8280000,12000000,12180000,9660000
12,9660000,9300000,5820000,7020000,9060000,2760000,2520000,7500000,4680000,4920000,6120000
13,59280000,41820000,45360000,33900000,37260000,42240000,59580000,60900000,59460000,52080000,65160000
14,113400000,152220000,91980000,91980000,78240000,79680000,76800000,77580000,72600000,86280000,78540000
15,60000,0,0,0,0,0,0,0,0,0,0
16,109080000,118920000,82560000,123300000,133740000,149460000,146100000,176160000,156240000,171120000,111060000
17,120000,60000,120000,0,60000,0,0,60000,0,0,60000
18,5640000,5460000,3420000,1500000,1500000,1320000,1080000,540000,1320000,2160000,1440000
19,280860000,291120000,246600000,209460000,229260000,198600000,207960000,198720000,223560000,226680000,209580000
20,18060000,17520000,21360000,8160000,21300000,17760000,16740000,31140000,26160000,12480000,26340000
21,60000,60000,60000,60000,60000,60000,60000,120000,120000,120000,60000
22,4320000,4380000,5220000,2460000,2220000,1920000,1500000,1440000,1260000,1020000,960000
23,119220000,172740000,143520000,162660000,145500000,166740000,143520000,173880000,198720000,195540000,185040000
24,217320000,253740000,223800000,213000000,222420000,218820000,169740000,214680000,199140000,202620000,180420000
25,306900000,321480000,314580000,257160000,287700000,327360000,404640000,316800000,248940000,344460000,474420000
26,1440000,1740000,1680000,1560000,1500000,1740000,900000,1500000,1380000,1260000,1500000
27,66840000,79680000,65760000,44160000,55200000,45240000,40380000,35820000,49020000,36480000,31500000
28,11460000,15300000,11880000,16680000,13980000,16020000,14220000,7200000,15120000,15480000,15840000
29,900000,240000,420000,360000,420000,0,60000,0,120000,120000,540000
30,27840000,12960000,5220000,8700000,7140000,7620000,5760000,10740000,5940000,11760000,2400000
31,3240000,3660000,3840000,2640000,2940000,1560000,1260000,1020000,1140000,1260000,1080000
32,261480000,318240000,199980000,158700000,155760000,141720000,119100000,154200000,174720000,146880000,170280000
33,0,0,0,0,120000,60000,60000,60000,120000,60000,120000
34,59040000,82020000,81900000,57300000,60780000,78660000,60180000,86700000,75540000,97500000,82440000
35,540000,420000,420000,300000,540000,360000,480000,1680000,540000,120000,60000
36,7080000,4320000,3420000,4980000,5160000,5940000,5400000,6420000,6540000,6840000,3540000
37,79200000,62580000,65700000,63420000,68820000,62880000,72000000,50940000,54540000,65760000,61620000
38,180000,300000,60000,1260000,1860000,1020000,1440000,1500000,1860000,60000,0
39,144420000,141720000,159780000,167340000,150180000,191040000,142140000,232860000,172740000,223980000,184440000
40,540000,300000,180000,420000,720000,1740000,2040000,2280000,1920000,240000,420000
41,18840000,16200000,16740000,19800000,14700000,27000000,14160000,23340000,15360000,19560000,18240000
42,1380000,2400000,2160000,4800000,2040000,1380000,1200000,3060000,3060000,1560000,6240000
43,1020000,120000,240000,180000,360000,420000,180000,420000,240000,120000,60000
44,38580000,44400000,51960000,29760000,52980000,33180000,42720000,43920000,48420000,49080000,69420000
45,29580000,58200000,68880000,15180000,10860000,25200000,22500000,32400000,21900000,10500000,11100000
46,0,60000,1920000,1800000,2760000,1320000,1080000,2940000,1860000,3000000,2580000
47,19260000,16980000,11580000,6000000,4320000,8940000,9840000,7080000,9300000,7260000,9120000
48,180000,180000,180000,120000,120000,120000,60000,60000,60000,60000,0
49,230460000,150780000,183600000,201480000,151320000,157620000,142140000,130380000,161580000,198660000,180840000
50,27840000,2280000,1560000,11520000,15600000,10200000,1320000,3900000,4200000,7500000,1080000
51,463620000,697080000,846360000,706260000,697860000,891540000,805920000,834300000,1076160000,966060000,1023120000
52,4080000,3480000,3960000,3660000,3300000,2700000,4680000,3660000,4320000,4020000,2340000
53,3060000,3900000,6900000,5940000,7800000,6240000,6360000,4680000,3240000,2880000,1980000
54,7860000,7020000,6300000,7140000,5820000,6780000,4260000,3240000,1920000,1380000,1080000

In [13]:
# imports
coffee_imp['1999'].isnull()
# coffee_imp.isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
Name: 1999, dtype: bool

In [14]:
# production
coffee_prod['1998/99'].isnull()
# coffee_prod.isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
Name: 1998/99, dtype: bool

### Observations
- While there are no "null" values, sometimes we have 0. Could be missing data.
- `coffee_prod` has column headers as string data types because of special characters: '1998/99'
- (note that this column name style differs from `coffee_exp` and `coffee_imp`)
- `coffee_prod` does not have its Country column in alphabetical order (starting with "Congo" at index 14)
- there is an additional column 'Coffee type' in `coffee_prod`
- note the float64 instead of int64 in `coffee_prod`
- Côte d'Ivoire and Cuba are swapped in `.sort_values()`, compared with `coffee_exp` list (manually fix?)
- eyeballing it, all import countries are different from export/production countries
- `print(coffee_exp.iloc[:, 0].to_list()[:10])` shows one string has double quotes instead of single quotes (but it's because of other characters)

In [15]:
#fix production "Country" labels out of order with sort_values()
coffee_prod = coffee_prod.sort_values(by="Country")

In [16]:
coffee_exp["Country"]
# coffee_imp["Country"].dtype
# coffee_prod["Country"].dtype

0                               Angola
1     Bolivia (Plurinational State of)
2                               Brazil
3                              Burundi
4                             Cameroon
5             Central African Republic
6                             Colombia
7                                Congo
8                           Costa Rica
9                        Côte d'Ivoire
10                                Cuba
11        Democratic Republic of Congo
12                  Dominican Republic
13                             Ecuador
14                         El Salvador
15                   Equatorial Guinea
16                            Ethiopia
17                               Gabon
18                               Ghana
19                           Guatemala
20                              Guinea
21                              Guyana
22                               Haiti
23                            Honduras
24                               India
25                           Indonesia
26                             Jamaica
27                               Kenya
28    Lao People's Democratic Republic
29                             Liberia
30                          Madagascar
31                              Malawi
32                              Mexico
33                               Nepal
34                           Nicaragua
35                             Nigeria
36                              Panama
37                    Papua New Guinea
38                            Paraguay
39                                Peru
40                         Philippines
41                              Rwanda
42                        Sierra Leone
43                           Sri Lanka
44                            Tanzania
45                            Thailand
46                         Timor-Leste
47                                Togo
48                   Trinidad & Tobago
49                              Uganda
50                           Venezuela
51                            Viet Nam
52                               Yemen
53                              Zambia
54                            Zimbabwe
Name: Country, dtype: str

In [17]:
# compare country names
pd.concat([coffee_exp["Country"],coffee_imp["Country"],coffee_prod["Country"].reset_index(drop=True)], axis="columns")

,Country,Country,Country
0,Angola,Austria,Angola
1,Bolivia (Plurinational State of),Belgium,Bolivia (Plurinational State of)
2,Brazil,Belgium/Luxembourg,Brazil
3,Burundi,Bulgaria,Burundi
4,Cameroon,Croatia,Cameroon
5,Central African Republic,Cyprus,Central African Republic
6,Colombia,Czechia,Colombia
7,Congo,Denmark,Congo
8,Costa Rica,Estonia,Costa Rica
9,Côte d'Ivoire,Finland,Cuba
10,Cuba,France,Côte d'Ivoire
11,Democratic Republic of Congo,Germany,Democratic Republic of Congo
12,Dominican Republic,Greece,Dominican Republic
13,Ecuador,Hungary,Ecuador
14,El Salvador,Ireland,El Salvador
15,Equatorial Guinea,Italy,Equatorial Guinea
16,Ethiopia,Latvia,Ethiopia
17,Gabon,Lithuania,Gabon
18,Ghana,Luxembourg,Ghana
19,Guatemala,Malta,Guatemala
20,Guinea,Netherlands,Guinea
21,Guyana,Poland,Guyana
22,Haiti,Portugal,Haiti
23,Honduras,Romania,Honduras
24,India,Slovakia,India
25,Indonesia,Slovenia,Indonesia
26,Jamaica,Spain,Jamaica
27,Kenya,Sweden,Kenya
28,Lao People's Democratic Republic,Japan,Lao People's Democratic Republic
29,Liberia,Norway,Liberia
30,Madagascar,Russian Federation,Madagascar
31,Malawi,Switzerland,Malawi
32,Mexico,Tunisia,Mexico
33,Nepal,United Kingdom,Nepal
34,Nicaragua,United States of America,Nicaragua
35,Nigeria,NaN,Nigeria
36,Panama,NaN,Panama
37,Papua New Guinea,NaN,Papua New Guinea
38,Paraguay,NaN,Paraguay
39,Peru,NaN,Peru
40,Philippines,NaN,Philippines
41,Rwanda,NaN,Rwanda
42,Sierra Leone,NaN,Sierra Leone
43,Sri Lanka,NaN,Sri Lanka
44,Tanzania,NaN,Tanzania
45,Thailand,NaN,Thailand
46,Timor-Leste,NaN,Timor-Leste
47,Togo,NaN,Togo
48,Trinidad & Tobago,NaN,Trinidad & Tobago
49,Uganda,NaN,Uganda
50,Venezuela,NaN,Venezuela
51,Viet Nam,NaN,Viet Nam
52,Yemen,NaN,Yemen
53,Zambia,NaN,Zambia
54,Zimbabwe,NaN,Zimbabwe

## Part 3 – Clean the Datasets

### 0. worksheet:

In [18]:
print(coffee_exp.index.tolist()[:10]) #shows pandas' placeholder index here: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(coffee_exp.index.dtype, coffee_exp.columns.dtype) #index is `int64`, column labels are `str`
print(type(coffee_exp)) #verifying that `<class 'pandas.DataFrame'>`
print(coffee_exp.index.is_unique) #expected since index is pandas' default ascending numeric values
print(coffee_exp.iloc[:, 0].to_list()[:10]) #iloc is "integer location" to get numeric position rather than by label
print(coffee_exp.iloc[:10,0]) #instead of printing a Python list ^ (to observe white space and odd types), here just print a Series

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
int64 str
<class 'pandas.DataFrame'>
True
['Angola', 'Bolivia (Plurinational State of)', 'Brazil', 'Burundi', 'Cameroon', 'Central African Republic', 'Colombia', 'Congo', 'Costa Rica', "Côte d'Ivoire"]
0                              Angola
1    Bolivia (Plurinational State of)
2                              Brazil
3                             Burundi
4                            Cameroon
5            Central African Republic
6                            Colombia
7                               Congo
8                          Costa Rica
9                       Côte d'Ivoire
Name: Country, dtype: str

### 1. Standardizing country name strings so they match across all three data frames perfectly before merging.

In [19]:
#check uniqueness of list
export_list = coffee_exp.iloc[:,0].is_unique
import_list = coffee_imp.iloc[:,0].is_unique
prod_list = coffee_prod.iloc[:,0].is_unique
print("EXPORTS: ", export_list, "  IMPORTS: ", import_list, "  PRODUCTION: ", prod_list)

EXPORTS:  True   IMPORTS:  True   PRODUCTION:  True

In [20]:
coffee_exp = coffee_exp.set_index("Country") #don't forget to assign the result back, or the new dataframe is lost
coffee_imp = coffee_imp.set_index("Country")
coffee_prod = coffee_prod.set_index("Country") 
coffee_exp

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
Country,,,,,,,,,,,,,,,,,,,,,
Angola,5040000,4260000,4800000,2340000,480000,2460000,3120000,3000000,3240000,3000000,...,480000,480000,360000,540000,660000,660000,540000,540000,1380000,43320000
Bolivia (Plurinational State of),9360000,4440000,5760000,2820000,5040000,5640000,7380000,6660000,5820000,7440000,...,4440000,3780000,3300000,3720000,1800000,1320000,1560000,1320000,1200000,137460000
Brazil,1016160000,1270980000,1127460000,1070280000,1036380000,868080000,915060000,1008060000,1088640000,1388940000,...,2028360000,1712940000,1899060000,-2147483648,-2147483648,2056140000,1855500000,2138220000,-2147483648,33807709056
Burundi,35100000,41280000,38760000,25080000,30480000,31680000,13440000,31740000,22440000,24540000,...,13080000,23520000,11700000,15120000,13800000,12240000,10140000,12120000,17580000,646200000
Cameroon,156660000,105120000,98760000,42300000,32760000,24420000,33840000,82080000,44760000,69240000,...,29400000,37320000,16320000,22500000,23400000,16860000,14700000,17220000,15000000,1399920000
Central African Republic,11820000,8460000,6000000,8220000,8220000,13920000,5880000,12180000,6120000,11700000,...,4680000,4680000,60000,4500000,2580000,4800000,1080000,2340000,1140000,170700000
Colombia,836640000,755940000,993840000,814080000,706080000,588840000,635280000,655140000,675600000,599700000,...,464040000,430200000,580200000,657240000,762960000,769860000,779100000,768480000,820320000,19878480000
Congo,120000,60000,0,60000,60000,1140000,780000,180000,0,0,...,0,0,0,0,0,0,0,0,0,2400000
Costa Rica,135960000,144000000,145860000,141840000,126300000,124020000,145800000,125940000,122700000,131700000,...,74580000,82440000,80640000,72540000,67680000,60420000,59220000,72480000,62340000,2991840000
Côte d'Ivoire,256980000,228300000,272760000,241980000,146640000,149640000,165060000,282780000,261900000,144360000,...,46320000,102720000,117720000,89340000,85080000,85920000,51300000,91320000,126240000,4721640000
Cuba,10920000,7260000,9780000,6960000,8160000,7320000,6720000,6420000,9120000,4620000,...,600000,900000,720000,780000,780000,900000,900000,1980000,1320000,111720000
Democratic Republic of Congo,110340000,85080000,57240000,55200000,45660000,63060000,52920000,32640000,38400000,29220000,...,7920000,8760000,8400000,9060000,7680000,10260000,5340000,11280000,12300000,775560000
Dominican Republic,32100000,28560000,22140000,19860000,19920000,27060000,27180000,18420000,21600000,9660000,...,5340000,8220000,3900000,2700000,1140000,1140000,1440000,1920000,1620000,316080000
Ecuador,107040000,84960000,76380000,95940000,128700000,92400000,92340000,62700000,63360000,59280000,...,91920000,94800000,75720000,67740000,52140000,55380000,41700000,28980000,30360000,1971720000
El Salvador,150600000,128880000,127200000,176820000,125580000,108420000,138840000,166320000,101040000,113400000,...,109560000,62640000,66180000,27720000,34560000,29760000,31620000,34260000,32760000,2716980000
Equatorial Guinea,420000,180000,180000,120000,60000,180000,120000,60000,120000,60000,...,0,0,0,0,0,0,0,0,0,1500000
Ethiopia,64440000,50460000,44040000,70020000,88500000,76560000,110280000,118800000,115020000,109080000,...,160500000,192180000,172200000,187020000,179100000,180060000,226380000,215340000,235260000,4163340000
Gabon,120000,180000,60000,120000,300000,180000,120000,0,120000,120000,...,60000,0,0,0,0,0,0,0,0,1800000
Ghana,660000,960000,1920000,2820000,660000,2280000,240000,1800000,1080000,5640000,...,4320000,1800000,1380000,1560000,2400000,1620000,1020000,720000,600000,53640000
Guatemala,194400000,169920000,199680000,225060000,196440000,222060000,238740000,254640000,212520000,280860000,...,221820000,225000000,214500000,182580000,177660000,179460000,202980000,199620000,216780000,6464340000
Guinea,7320000,3660000,3480000,900000,3000000,9120000,1920000,6840000,13680000,18060000,...,23100000,22620000,8040000,1440000,9120000,15000000,12960000,9420000,4140000,397140000
Guyana,0,0,60000,0,0,0,0,0,0,60000,...,60000,120000,60000,780000,120000,120000,60000,60000,60000,2400000
Haiti,11460000,9060000,9960000,9540000,6180000,9120000,9360000,6060000,7620000,4320000,...,540000,660000,480000,180000,180000,60000,120000,120000,120000,108060000
Honduras,104100000,86640000,117600000,102300000,103080000,107760000,123600000,103320000,139740000,119220000,...,236820000,330480000,251100000,255120000,301800000,318360000,440460000,428640000,405900000,5964840000
India,118740000,103620000,108960000,126120000,149760000,148020000,186180000,158400000,209220000,217320000,...,324840000,302640000,301980000,307860000,315720000,365160000,392520000,358020000,361680000,6933960000
Indonesia,414180000,370260000,276240000,339720000,276300000,236820000,386400000,345300000,335880000,306900000,...,235200000,492360000,555300000,370500000,502740000,392700000,491880000,272340000,380040000,10607940000
Jamaica,900000,1020000,1320000,1440000,960000,1560000,1620000,1800000,1020000,1440000,...,960000,900000,900000,600000,720000,660000,600000,600000,540000,35220000
Kenya,118140000,93480000,83040000,86340000,81480000,87000000,114120000,69540000,50460000,66840000,...,36540000,48180000,48900000,47940000,42720000,43620000,42600000,45180000,50160000,1771380000
Lao People's Democratic Republic,5880000,5880000,6120000,8520000,9180000,9900000,8640000,6600000,6720000,11460000,...,25260000,21600000,24000000,22200000,24180000,23160000,23160000,21660000,34500000,457620000
Liberia,1320000,0,0,0,0,0,0,0,180000,900000,...,480000,180000,240000,60000,240000,180000,660000,480000,60000,7680000
Madagascar,51780000,35280000,44160000,37680000,26160000,35100000,43080000,28800000,47760000,27840000,...,8640000,4740000,9960000,8280000,3540000,4560000,3480000,360000,240000,504120000
Malawi,7440000,6000000,7680000,6240000,4680000,5520000,3600000,3600000,3540000,3240000,...,1560000,1200000,1740000,1560000,1080000,1320000,780000,720000,960000,83340000
Mexico,220980000,211860000,199920000,195840000,167340000,217560000,277980000,270120000,203940000,261480000,...,174420000,213360000,187920000,148800000,147480000,133980000,174660000,173280000,157620000,5628000000
Nepal,0,0,0,0,0,0,0,0,0,0,...,240000,60000,60000,60000,120000,120000,60000,120000,60000,1560000
Nicaragua,40260000,23520000,38160000,28560000,37440000,40860000,49320000,42840000,56460000,59040000,...,88080000,119220000,99660000,114060000,105180000,117780000,146940000,138000000,177240000,2388360000
Nigeria,240000,60000,660000,600000,480000,900000,420000,420000,600000,540000,...,420000,120000,60000,60000,180000,60000,180000,180000,120000,11400000
Panama,7920000,7440000,7500000,7740000,4560000,10860000,8340000,7440000,8700000,7080000,...,3180000,3060000,2940000,3060000,3000000,3360000,3000000,2820000,3060000,161520000
Papua New Guinea,63060000,47280000,55020000,63300000,69420000,60120000,65400000,62580000,80940000,79200000,...,73500000,55500000,48660000,48420000,42660000,67980000,47640000,52200000,47220000,1814100000
Paraguay,15780000,7200000,2400000,3480000,2880000,1260000,960000,2100000,1140000,180000,...,0,0,0,0,0,0,0,0,0,46740000
Peru,66300000,62520000,63660000,46500000,63420000,105600000,100740000,98880000,116940000,144420000,...,281820000,258600000,224160000,163200000,167400000,237600000,236760000,243840000,226320000,4903920000
Philippines,10080000,6180000,2460000,2100000,7560000,3420000,1620000,1860000,1260000,540000,...,600000,180000,360000,720000,900000,780000,540000,240000,420000,52440000
Rwanda,46740000,28440000,38700000,28860000,1800000,18840000,15900000,13080000,12840000,18840000,...,16620000,15060000,15240000,15360000,15780000,14640000,14760000,21000000,23340000,578700000
Sierra Leone,8400000,6240000,2820000,2460000,3720000,4260000,1740000,2820000,2520000,1380000,...,2220000,3900000,3420000,1440000,3240000,1560000,2100000,1620000,2820000,90060000
Sri Lanka,1140000,1320000,900000,840000,2820000,1320000,720000,1260000,1620000,1020000,...,120000,0,0,120000,0,60000,120000,120000,60000,16020000
Tanzania,61140000,52260000,49680000,62220000,37920000,44700000,58200000,39300000,44520000,38580000,...,47880000,45360000,56100000,43080000,42540000,54300000,39840000,51360000,64140000,1432320000
Thailand,60060000,32460000,69840000,58920000,68160000,72600000,52380000,63960000,46680000,29580000,...,14580000,21000000,2940000,1620000,34680000,7860000,8460000,15480000,10440000,970620000
Timor-Leste,0,0,0,0,0,0,0,0,0,0,...,2340000,3360000,4200000,6660000,4080000,4080000,5160000,7740000,7020000,68040000
Togo,14340000,9300000,18780000,13080000,9960000,12000000,5100000,18780000,9960000,19260000,...,9300000,8820000,5460000,8040000,10680000,4500000,1620000,6660000,3480000,291420000
Trinidad & Tobago,1800000,480000,120000,600000,300000,240000,240000,240000,300000,180000,...,0,60000,120000,120000,120000,120000,120000,180000,120000,6480000
Uganda,141180000,125700000,117660000,109740000,202140000,184740000,279300000,210120000,197160000,230460000,...,188520000,161100000,220320000,206520000,215760000,212580000,286440000,253380000,271560000,5632200000
Venezuela,16680000,7680000,8160000,31500000,23160000,5820000,29700000,6300000,16080000,27840000,...,0,120000,360000,0,60000,0,0,4320000,3180000,241260000
Viet Nam,68700000,72060000,116280000,124320000,163260000,212760000,226740000,370680000,388020000,463620000,...,1063020000,1375200000,1183080000,1565820000,1316640000,1783260000,1505520000,1883100000,1644000000,24924480000
Yemen,3000000,4320000,2220000,3060000,5580000,4620000,2520000,4800000,4260000,4080000,...,2100000,3780000,3300000,3420000,3120000,2280000,2760000,2520000,720000,101220000
Zambia,1440000,1740000,1860000,1380000,1440000,1260000,2160000,2340000,1980000,3060000,...,540000,420000,600000,300000,180000,600000,780000,1560000,1620000,76260000
Zimbabwe,15060000,14340000,9720000,4200000,1920000,9420000,9000000,6540000,9180000,7860000,...,300000,240000,120000,660000,660000,720000,120000,300000,360000,136080000

In [21]:
# write an index cleaning function
def cleanUpCountryLabels(indx):
    newindx = indx.astype(str).str.strip().str.upper() #check for non-string types, stripe white space, change all to upper-case 
    return newindx

coffee_exp.index = cleanUpCountryLabels(coffee_exp.index)
coffee_imp.index = cleanUpCountryLabels(coffee_imp.index)
coffee_prod.index = cleanUpCountryLabels(coffee_prod.index)

In [22]:
coffee_exp.index
coffee_imp.index
coffee_prod.index

Index(['ANGOLA', 'BOLIVIA (PLURINATIONAL STATE OF)', 'BRAZIL', 'BURUNDI',
       'CAMEROON', 'CENTRAL AFRICAN REPUBLIC', 'COLOMBIA', 'CONGO',
       'COSTA RICA', 'CUBA', 'CÔTE D'IVOIRE', 'DEMOCRATIC REPUBLIC OF CONGO',
       'DOMINICAN REPUBLIC', 'ECUADOR', 'EL SALVADOR', 'EQUATORIAL GUINEA',
       'ETHIOPIA', 'GABON', 'GHANA', 'GUATEMALA', 'GUINEA', 'GUYANA', 'HAITI',
       'HONDURAS', 'INDIA', 'INDONESIA', 'JAMAICA', 'KENYA',
       'LAO PEOPLE'S DEMOCRATIC REPUBLIC', 'LIBERIA', 'MADAGASCAR', 'MALAWI',
       'MEXICO', 'NEPAL', 'NICARAGUA', 'NIGERIA', 'PANAMA', 'PAPUA NEW GUINEA',
       'PARAGUAY', 'PERU', 'PHILIPPINES', 'RWANDA', 'SIERRA LEONE',
       'SRI LANKA', 'TANZANIA', 'THAILAND', 'TIMOR-LESTE', 'TOGO',
       'TRINIDAD & TOBAGO', 'UGANDA', 'VENEZUELA', 'VIET NAM', 'YEMEN',
       'ZAMBIA', 'ZIMBABWE'],
      dtype='str', name='Country')

### 2. Standardizing column names to int for range and calculations

In [23]:
#checks
coffee_exp.columns.is_unique
coffee_exp.columns.dtype
coffee_exp.columns
#cleaning
coffee_exp.columns = coffee_exp.columns.str.strip()
years = pd.to_numeric(coffee_exp.columns[:-1])
coffee_exp.columns = list(years) + [coffee_exp.columns[-1]] #make years a list so that it joins the columns list
coffee_exp.columns

Index([          1990,           1991,           1992,           1993,
                 1994,           1995,           1996,           1997,
                 1998,           1999,           2000,           2001,
                 2002,           2003,           2004,           2005,
                 2006,           2007,           2008,           2009,
                 2010,           2011,           2012,           2013,
                 2014,           2015,           2016,           2017,
                 2018,           2019, 'Total_export'],
      dtype='object')

In [24]:
#checks
coffee_imp.columns.is_unique
coffee_imp.columns.dtype
coffee_imp.columns
#cleaning
coffee_imp.columns = coffee_imp.columns.str.strip()
years = pd.to_numeric(coffee_imp.columns[:-1])
coffee_imp.columns = list(years) + [coffee_imp.columns[-1]]
coffee_imp.columns

Index([          1990,           1991,           1992,           1993,
                 1994,           1995,           1996,           1997,
                 1998,           1999,           2000,           2001,
                 2002,           2003,           2004,           2005,
                 2006,           2007,           2008,           2009,
                 2010,           2011,           2012,           2013,
                 2014,           2015,           2016,           2017,
                 2018,           2019, 'Total_import'],
      dtype='object')

In [25]:
#checks
coffee_prod.columns.is_unique
coffee_prod.columns.inferred_type
coffee_prod.columns
#cleaning
coffee_prod.columns = coffee_prod.columns.str.strip() #only select year columns for range utility
years = pd.to_numeric(coffee_prod.columns[1:-1].str[:4]) #use .str to remove mismatched string endings: '1990/91' -> 1990
coffee_prod.columns = [coffee_prod.columns[0]] + list(years) + [coffee_prod.columns[-1]]
coffee_prod.columns

Index([     'Coffee type',               1990,               1991,
                     1992,               1993,               1994,
                     1995,               1996,               1997,
                     1998,               1999,               2000,
                     2001,               2002,               2003,
                     2004,               2005,               2006,
                     2007,               2008,               2009,
                     2010,               2011,               2012,
                     2013,               2014,               2015,
                     2016,               2017,               2018,
                     2019, 'Total_production'],
      dtype='object')

### 3. Programmatically stripping whitespaces or commas from numeric columns and converting them using pd.to_numeric().

In [ ]:
print(coffee_exp.columns.tolist())
coffee_exp = coffee_exp.apply(pd.to_numeric, errors="coerce")
print(coffee_exp.columns.tolist())
coffee_exp

In [27]:
# print(coffee_exp.columns.tolist())
coffee_imp = coffee_imp.apply(pd.to_numeric, errors="coerce")
# print(coffee_exp.columns.tolist())
coffee_imp

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_import
Country,,,,,,,,,,,,,,,,,,,,,
AUSTRIA,112800000,123480000,132360000,110160000,85020000,73860000,72600000,77640000,77580000,90000000,...,87120000,93540000,93300000,91500000,90780000,89700000,87600000,85740000,86880000,2765760000
BELGIUM,0,0,0,0,0,0,0,0,0,180180000,...,349680000,340080000,330120000,312720000,332040000,363120000,340620000,344520000,371940000,6240540000
BELGIUM/LUXEMBOURG,120900000,104760000,109680000,123780000,135720000,144060000,151560000,152640000,214800000,0,...,0,0,0,0,0,0,0,0,0,1257900000
BULGARIA,16080000,12000000,10920000,23820000,27780000,30900000,16320000,17640000,20520000,22020000,...,28920000,33600000,36540000,37260000,40920000,46740000,42420000,44220000,47100000,830700000
CROATIA,0,0,10080000,9780000,11580000,19200000,19320000,23100000,20340000,21120000,...,23460000,23040000,24780000,25200000,26220000,28740000,26340000,26760000,27960000,622080000
CYPRUS,3000000,3240000,2460000,4620000,3120000,2640000,3120000,2460000,3000000,3300000,...,4920000,5040000,5640000,5640000,5340000,5580000,6000000,7980000,7980000,130380000
CZECHIA,39540000,31500000,28500000,30840000,33240000,33180000,31500000,33600000,45900000,43680000,...,57120000,67620000,71040000,109380000,124080000,106740000,90420000,114180000,96540000,1816020000
DENMARK,57540000,58980000,63720000,59640000,61980000,52620000,60360000,56940000,60840000,65640000,...,54540000,54780000,55260000,51180000,50460000,54360000,51120000,52080000,54480000,1741860000
ESTONIA,0,0,960000,3060000,4980000,6420000,7020000,8460000,8100000,7860000,...,10020000,9420000,9360000,7860000,7560000,8100000,7980000,8820000,8880000,268980000
FINLAND,65700000,61980000,63300000,78060000,81660000,46140000,59520000,71160000,70080000,72540000,...,77220000,74280000,76500000,72780000,79260000,83340000,81600000,77100000,90900000,2151840000
FRANCE,378060000,393180000,396720000,380040000,382140000,372840000,399600000,402240000,394560000,400560000,...,419520000,410460000,402780000,426720000,408540000,404280000,418020000,457440000,479580000,11972520000
GERMANY,820260000,793740000,827340000,846420000,814980000,771120000,810420000,834300000,824400000,859200000,...,1255560000,1308960000,1270440000,1324680000,1278960000,1342080000,1305900000,1328820000,1345920000,31481400000
GREECE,38520000,24420000,20940000,22500000,30120000,31380000,45960000,47340000,42240000,43980000,...,69300000,74640000,76140000,74040000,72600000,95040000,52020000,69600000,74760000,1640040000
HUNGARY,34440000,38460000,31320000,40080000,46260000,31200000,36180000,40500000,42960000,45720000,...,38400000,44880000,33420000,49980000,42840000,43500000,43320000,46740000,46380000,1327440000
IRELAND,7740000,7080000,5700000,6660000,7860000,6900000,5880000,6360000,6120000,8520000,...,12600000,15120000,13980000,17520000,21420000,24180000,25620000,26400000,26280000,384300000
ITALY,314520000,277800000,275700000,335640000,333240000,323280000,336480000,344580000,353340000,356580000,...,501300000,521460000,529380000,561000000,559680000,613440000,601200000,638340000,654840000,13272120000
LATVIA,0,0,1200000,3600000,1380000,1800000,3960000,8640000,9540000,10980000,...,8460000,9420000,9660000,12780000,12120000,13860000,13740000,14580000,14100000,261540000
LITHUANIA,0,0,120000,540000,2820000,6780000,9000000,11220000,11100000,12360000,...,17340000,20220000,21720000,23760000,25680000,29940000,25920000,26460000,28440000,473460000
LUXEMBOURG,0,0,0,0,0,0,0,0,0,8700000,...,19560000,19380000,22680000,24780000,22560000,23640000,22800000,25980000,24120000,415620000
MALTA,1260000,960000,1080000,1380000,780000,1380000,540000,540000,600000,540000,...,1020000,1260000,1320000,1500000,960000,1140000,1020000,1140000,1380000,29700000
NETHERLANDS,187680000,187260000,192300000,168240000,168000000,174600000,185040000,175440000,171720000,153960000,...,160680000,163800000,204420000,240960000,250560000,286860000,304080000,331200000,321240000,5951400000
POLAND,26100000,15000000,107220000,100200000,110580000,106260000,115440000,135180000,137580000,144240000,...,204240000,212580000,197040000,193740000,219960000,229620000,239940000,259500000,267120000,4815540000
PORTUGAL,33120000,33420000,35460000,39960000,39840000,37980000,44580000,43620000,45720000,49020000,...,63480000,64560000,63780000,63600000,62640000,67680000,65640000,68400000,73200000,1568700000
ROMANIA,26520000,20100000,36180000,25500000,20820000,33060000,41820000,37860000,35700000,30660000,...,50640000,54180000,58260000,57480000,60720000,68040000,69300000,70440000,69900000,1380180000
SLOVAKIA,0,0,0,17280000,15420000,15000000,15660000,15180000,15540000,16140000,...,46620000,46320000,47880000,55140000,54600000,54360000,43380000,53400000,46380000,821760000
SLOVENIA,0,0,7380000,9120000,9540000,8880000,10500000,10260000,10440000,10920000,...,13380000,13260000,15480000,16140000,16320000,19380000,24060000,33000000,37200000,395520000
SPAIN,183180000,178200000,204840000,168780000,181680000,188760000,210900000,226620000,223080000,239160000,...,289260000,305640000,308220000,324360000,325740000,339600000,324840000,340380000,359040000,7840620000
SWEDEN,106020000,103020000,106320000,105420000,113580000,85200000,91320000,88380000,86400000,87360000,...,98820000,100800000,102540000,131880000,127260000,141000000,138360000,135720000,140880000,3148800000
JAPAN,319800000,330600000,319560000,341460000,373020000,329340000,359640000,355260000,361620000,392820000,...,452640000,421500000,502860000,459420000,483780000,481560000,458820000,452400000,482400000,12422760000
NORWAY,44520000,45660000,44340000,41580000,48360000,39720000,43200000,41040000,42420000,47400000,...,47700000,44100000,46860000,44580000,48000000,47940000,48060000,44580000,47160000,1334340000
RUSSIAN FEDERATION,0,0,82920000,107700000,103560000,103680000,67680000,131100000,103920000,82080000,...,253080000,250500000,264600000,284820000,282600000,313980000,328080000,317280000,355020000,5731080000
SWITZERLAND,70260000,67800000,66060000,63600000,65940000,61020000,66720000,58260000,66720000,68340000,...,149880000,148680000,160020000,158580000,164880000,168960000,174240000,185160000,193680000,3212700000
TUNISIA,6060000,5400000,6660000,6060000,8220000,8220000,8640000,9900000,8820000,11160000,...,25740000,26340000,26340000,27600000,27540000,27960000,32760000,31980000,30480000,492540000
UNITED KINGDOM,173880000,168360000,185280000,191820000,207960000,168420000,174180000,175740000,188520000,174420000,...,250980000,247560000,252360000,259140000,293700000,303120000,299340000,341280000,333240000,6731460000
UNITED STATES OF AMERICA,1260420000,1190400000,1376340000,1159740000,970260000,1026420000,1166700000,1220580000,1261800000,1364760000,...,1565580000,1563360000,1620960000,1653900000,1662480000,1730280000,1769280000,1735080000,1851240000,42507660000

In [28]:
# print(coffee_exp.columns.tolist())
coffee_prod = coffee_exp.apply(pd.to_numeric, errors="coerce")
# print(coffee_exp.columns.tolist())
coffee_prod

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
Country,,,,,,,,,,,,,,,,,,,,,
ANGOLA,5040000,4260000,4800000,2340000,480000,2460000,3120000,3000000,3240000,3000000,...,480000,480000,360000,540000,660000,660000,540000,540000,1380000,43320000
BOLIVIA (PLURINATIONAL STATE OF),9360000,4440000,5760000,2820000,5040000,5640000,7380000,6660000,5820000,7440000,...,4440000,3780000,3300000,3720000,1800000,1320000,1560000,1320000,1200000,137460000
BRAZIL,1016160000,1270980000,1127460000,1070280000,1036380000,868080000,915060000,1008060000,1088640000,1388940000,...,2028360000,1712940000,1899060000,-2147483648,-2147483648,2056140000,1855500000,2138220000,-2147483648,33807709056
BURUNDI,35100000,41280000,38760000,25080000,30480000,31680000,13440000,31740000,22440000,24540000,...,13080000,23520000,11700000,15120000,13800000,12240000,10140000,12120000,17580000,646200000
CAMEROON,156660000,105120000,98760000,42300000,32760000,24420000,33840000,82080000,44760000,69240000,...,29400000,37320000,16320000,22500000,23400000,16860000,14700000,17220000,15000000,1399920000
CENTRAL AFRICAN REPUBLIC,11820000,8460000,6000000,8220000,8220000,13920000,5880000,12180000,6120000,11700000,...,4680000,4680000,60000,4500000,2580000,4800000,1080000,2340000,1140000,170700000
COLOMBIA,836640000,755940000,993840000,814080000,706080000,588840000,635280000,655140000,675600000,599700000,...,464040000,430200000,580200000,657240000,762960000,769860000,779100000,768480000,820320000,19878480000
CONGO,120000,60000,0,60000,60000,1140000,780000,180000,0,0,...,0,0,0,0,0,0,0,0,0,2400000
COSTA RICA,135960000,144000000,145860000,141840000,126300000,124020000,145800000,125940000,122700000,131700000,...,74580000,82440000,80640000,72540000,67680000,60420000,59220000,72480000,62340000,2991840000
CÔTE D'IVOIRE,256980000,228300000,272760000,241980000,146640000,149640000,165060000,282780000,261900000,144360000,...,46320000,102720000,117720000,89340000,85080000,85920000,51300000,91320000,126240000,4721640000
CUBA,10920000,7260000,9780000,6960000,8160000,7320000,6720000,6420000,9120000,4620000,...,600000,900000,720000,780000,780000,900000,900000,1980000,1320000,111720000
DEMOCRATIC REPUBLIC OF CONGO,110340000,85080000,57240000,55200000,45660000,63060000,52920000,32640000,38400000,29220000,...,7920000,8760000,8400000,9060000,7680000,10260000,5340000,11280000,12300000,775560000
DOMINICAN REPUBLIC,32100000,28560000,22140000,19860000,19920000,27060000,27180000,18420000,21600000,9660000,...,5340000,8220000,3900000,2700000,1140000,1140000,1440000,1920000,1620000,316080000
ECUADOR,107040000,84960000,76380000,95940000,128700000,92400000,92340000,62700000,63360000,59280000,...,91920000,94800000,75720000,67740000,52140000,55380000,41700000,28980000,30360000,1971720000
EL SALVADOR,150600000,128880000,127200000,176820000,125580000,108420000,138840000,166320000,101040000,113400000,...,109560000,62640000,66180000,27720000,34560000,29760000,31620000,34260000,32760000,2716980000
EQUATORIAL GUINEA,420000,180000,180000,120000,60000,180000,120000,60000,120000,60000,...,0,0,0,0,0,0,0,0,0,1500000
ETHIOPIA,64440000,50460000,44040000,70020000,88500000,76560000,110280000,118800000,115020000,109080000,...,160500000,192180000,172200000,187020000,179100000,180060000,226380000,215340000,235260000,4163340000
GABON,120000,180000,60000,120000,300000,180000,120000,0,120000,120000,...,60000,0,0,0,0,0,0,0,0,1800000
GHANA,660000,960000,1920000,2820000,660000,2280000,240000,1800000,1080000,5640000,...,4320000,1800000,1380000,1560000,2400000,1620000,1020000,720000,600000,53640000
GUATEMALA,194400000,169920000,199680000,225060000,196440000,222060000,238740000,254640000,212520000,280860000,...,221820000,225000000,214500000,182580000,177660000,179460000,202980000,199620000,216780000,6464340000
GUINEA,7320000,3660000,3480000,900000,3000000,9120000,1920000,6840000,13680000,18060000,...,23100000,22620000,8040000,1440000,9120000,15000000,12960000,9420000,4140000,397140000
GUYANA,0,0,60000,0,0,0,0,0,0,60000,...,60000,120000,60000,780000,120000,120000,60000,60000,60000,2400000
HAITI,11460000,9060000,9960000,9540000,6180000,9120000,9360000,6060000,7620000,4320000,...,540000,660000,480000,180000,180000,60000,120000,120000,120000,108060000
HONDURAS,104100000,86640000,117600000,102300000,103080000,107760000,123600000,103320000,139740000,119220000,...,236820000,330480000,251100000,255120000,301800000,318360000,440460000,428640000,405900000,5964840000
INDIA,118740000,103620000,108960000,126120000,149760000,148020000,186180000,158400000,209220000,217320000,...,324840000,302640000,301980000,307860000,315720000,365160000,392520000,358020000,361680000,6933960000
INDONESIA,414180000,370260000,276240000,339720000,276300000,236820000,386400000,345300000,335880000,306900000,...,235200000,492360000,555300000,370500000,502740000,392700000,491880000,272340000,380040000,10607940000
JAMAICA,900000,1020000,1320000,1440000,960000,1560000,1620000,1800000,1020000,1440000,...,960000,900000,900000,600000,720000,660000,600000,600000,540000,35220000
KENYA,118140000,93480000,83040000,86340000,81480000,87000000,114120000,69540000,50460000,66840000,...,36540000,48180000,48900000,47940000,42720000,43620000,42600000,45180000,50160000,1771380000
LAO PEOPLE'S DEMOCRATIC REPUBLIC,5880000,5880000,6120000,8520000,9180000,9900000,8640000,6600000,6720000,11460000,...,25260000,21600000,24000000,22200000,24180000,23160000,23160000,21660000,34500000,457620000
LIBERIA,1320000,0,0,0,0,0,0,0,180000,900000,...,480000,180000,240000,60000,240000,180000,660000,480000,60000,7680000
MADAGASCAR,51780000,35280000,44160000,37680000,26160000,35100000,43080000,28800000,47760000,27840000,...,8640000,4740000,9960000,8280000,3540000,4560000,3480000,360000,240000,504120000
MALAWI,7440000,6000000,7680000,6240000,4680000,5520000,3600000,3600000,3540000,3240000,...,1560000,1200000,1740000,1560000,1080000,1320000,780000,720000,960000,83340000
MEXICO,220980000,211860000,199920000,195840000,167340000,217560000,277980000,270120000,203940000,261480000,...,174420000,213360000,187920000,148800000,147480000,133980000,174660000,173280000,157620000,5628000000
NEPAL,0,0,0,0,0,0,0,0,0,0,...,240000,60000,60000,60000,120000,120000,60000,120000,60000,1560000
NICARAGUA,40260000,23520000,38160000,28560000,37440000,40860000,49320000,42840000,56460000,59040000,...,88080000,119220000,99660000,114060000,105180000,117780000,146940000,138000000,177240000,2388360000
NIGERIA,240000,60000,660000,600000,480000,900000,420000,420000,600000,540000,...,420000,120000,60000,60000,180000,60000,180000,180000,120000,11400000
PANAMA,7920000,7440000,7500000,7740000,4560000,10860000,8340000,7440000,8700000,7080000,...,3180000,3060000,2940000,3060000,3000000,3360000,3000000,2820000,3060000,161520000
PAPUA NEW GUINEA,63060000,47280000,55020000,63300000,69420000,60120000,65400000,62580000,80940000,79200000,...,73500000,55500000,48660000,48420000,42660000,67980000,47640000,52200000,47220000,1814100000
PARAGUAY,15780000,7200000,2400000,3480000,2880000,1260000,960000,2100000,1140000,180000,...,0,0,0,0,0,0,0,0,0,46740000
PERU,66300000,62520000,63660000,46500000,63420000,105600000,100740000,98880000,116940000,144420000,...,281820000,258600000,224160000,163200000,167400000,237600000,236760000,243840000,226320000,4903920000
PHILIPPINES,10080000,6180000,2460000,2100000,7560000,3420000,1620000,1860000,1260000,540000,...,600000,180000,360000,720000,900000,780000,540000,240000,420000,52440000
RWANDA,46740000,28440000,38700000,28860000,1800000,18840000,15900000,13080000,12840000,18840000,...,16620000,15060000,15240000,15360000,15780000,14640000,14760000,21000000,23340000,578700000
SIERRA LEONE,8400000,6240000,2820000,2460000,3720000,4260000,1740000,2820000,2520000,1380000,...,2220000,3900000,3420000,1440000,3240000,1560000,2100000,1620000,2820000,90060000
SRI LANKA,1140000,1320000,900000,840000,2820000,1320000,720000,1260000,1620000,1020000,...,120000,0,0,120000,0,60000,120000,120000,60000,16020000
TANZANIA,61140000,52260000,49680000,62220000,37920000,44700000,58200000,39300000,44520000,38580000,...,47880000,45360000,56100000,43080000,42540000,54300000,39840000,51360000,64140000,1432320000
THAILAND,60060000,32460000,69840000,58920000,68160000,72600000,52380000,63960000,46680000,29580000,...,14580000,21000000,2940000,1620000,34680000,7860000,8460000,15480000,10440000,970620000
TIMOR-LESTE,0,0,0,0,0,0,0,0,0,0,...,2340000,3360000,4200000,6660000,4080000,4080000,5160000,7740000,7020000,68040000
TOGO,14340000,9300000,18780000,13080000,9960000,12000000,5100000,18780000,9960000,19260000,...,9300000,8820000,5460000,8040000,10680000,4500000,1620000,6660000,3480000,291420000
TRINIDAD & TOBAGO,1800000,480000,120000,600000,300000,240000,240000,240000,300000,180000,...,0,60000,120000,120000,120000,120000,120000,180000,120000,6480000
UGANDA,141180000,125700000,117660000,109740000,202140000,184740000,279300000,210120000,197160000,230460000,...,188520000,161100000,220320000,206520000,215760000,212580000,286440000,253380000,271560000,5632200000
VENEZUELA,16680000,7680000,8160000,31500000,23160000,5820000,29700000,6300000,16080000,27840000,...,0,120000,360000,0,60000,0,0,4320000,3180000,241260000
VIET NAM,68700000,72060000,116280000,124320000,163260000,212760000,226740000,370680000,388020000,463620000,...,1063020000,1375200000,1183080000,1565820000,1316640000,1783260000,1505520000,1883100000,1644000000,24924480000
YEMEN,3000000,4320000,2220000,3060000,5580000,4620000,2520000,4800000,4260000,4080000,...,2100000,3780000,3300000,3420000,3120000,2280000,2760000,2520000,720000,101220000
ZAMBIA,1440000,1740000,1860000,1380000,1440000,1260000,2160000,2340000,1980000,3060000,...,540000,420000,600000,300000,180000,600000,780000,1560000,1620000,76260000
ZIMBABWE,15060000,14340000,9720000,4200000,1920000,9420000,9000000,6540000,9180000,7860000,...,300000,240000,120000,660000,660000,720000,120000,300000,360000,136080000

In [ ]:
# adding nan

### Part 4 – Business & Trade Questions

#### 1. Largest change in production.

In [29]:
change = coffee_prod[-1] - coffee_prod[1]

KeyError: -1

#### 2. Trade balance.

#### 3. Production by coffee type.

#### 4. Exporters with no production.

### Part 5 – Visualizations

### Part 6 – Executive Summary